name: AstraItemStats
version: ${project.version} (build ${project.BUILD_NUMBER}-${project.BUILD_TYPE})
main: me.darkcray_.astraItemStats.AstraItemStats
api-version: '26.1.2'
authors: [ DarkCray_ ]
commands:
  astraitemstats:
    description: Main command of the plugin AstraItemStats
    usage: §6Use /astraitemstats <reload|menu>
    aliases:
     - ait
     - st
    permission: astraitemstats.admin
